import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

// Translation keys used throughout the Chat App UI. Each locale below
// mirrors the same key set so missing translations fall back predictably
// to `fallbackLng` instead of leaking raw keys onto the page.
const keys = {
  en: {
    'Login': 'Login',
    'Register': 'Register',
    'Chat Rooms': 'Chat Rooms',
    'Create Chat Room': 'Create Chat Room',
    'Log Out': 'Log Out',
    'Language': 'Language',
    'Username': 'Username',
    'Password': 'Password',
    'Username is required': 'Username is required',
    'Password is required': 'Password is required',
    'Login successful': 'Login successful',
    'Login failed': 'Login failed',
    "Don't have an account?": "Don't have an account?",
    'Registration successful': 'Registration successful',
    'Registration failed': 'Registration failed',
    'Username must be at least 3 characters': 'Username must be at least 3 characters',
    'Password must be at least 8 characters': 'Password must be at least 8 characters',
    'Already have an account?': 'Already have an account?',
    'Room name is required': 'Room name is required',
    'Chat room "{{name}}" created': 'Chat room "{{name}}" created',
    'Failed to create room': 'Failed to create room',
    'Enter room name': 'Enter room name',
    'No rooms yet. Create the first one!': 'No rooms yet. Create the first one!',
    'Join': 'Join',
    'Failed to load rooms': 'Failed to load rooms',
    'Failed to load room': 'Failed to load room',
    'Connection lost': 'Connection lost',
    'You': 'You',
    'Send Message': 'Send Message',
    'Loading...': 'Loading...',
    'Welcome to the Chat Application': 'Welcome to the Chat Application',
    'Create an account or log in to join real-time chat rooms.':
      'Create an account or log in to join real-time chat rooms.',
  },
  es: {
    'Login': 'Iniciar sesión',
    'Register': 'Registrarse',
    'Chat Rooms': 'Salas de Chat',
    'Create Chat Room': 'Crear Sala de Chat',
    'Log Out': 'Cerrar Sesión',
    'Language': 'Idioma',
    'Username': 'Usuario',
    'Password': 'Contraseña',
    'Username is required': 'El usuario es obligatorio',
    'Password is required': 'La contraseña es obligatoria',
    'Login successful': 'Inicio de sesión correcto',
    'Login failed': 'Error al iniciar sesión',
    "Don't have an account?": '¿No tienes una cuenta?',
    'Registration successful': 'Registro exitoso',
    'Registration failed': 'Error en el registro',
    'Username must be at least 3 characters': 'El usuario debe tener al menos 3 caracteres',
    'Password must be at least 8 characters': 'La contraseña debe tener al menos 8 caracteres',
    'Already have an account?': '¿Ya tienes una cuenta?',
    'Room name is required': 'El nombre de la sala es obligatorio',
    'Chat room "{{name}}" created': 'Sala de chat "{{name}}" creada',
    'Failed to create room': 'Error al crear la sala',
    'Enter room name': 'Introduce el nombre de la sala',
    'No rooms yet. Create the first one!': 'Todavía no hay salas. ¡Crea la primera!',
    'Join': 'Unirse',
    'Failed to load rooms': 'Error al cargar las salas',
    'Failed to load room': 'Error al cargar la sala',
    'Connection lost': 'Conexión perdida',
    'You': 'Tú',
    'Send Message': 'Enviar Mensaje',
    'Loading...': 'Cargando...',
    'Welcome to the Chat Application': 'Bienvenido a la aplicación de chat',
    'Create an account or log in to join real-time chat rooms.':
      'Crea una cuenta o inicia sesión para unirte a salas de chat en tiempo real.',
  },
  fr: {
    'Login': 'Connexion',
    'Register': "S'inscrire",
    'Chat Rooms': 'Salons de discussion',
    'Create Chat Room': 'Créer un salon',
    'Log Out': 'Se déconnecter',
    'Language': 'Langue',
    'Username': "Nom d'utilisateur",
    'Password': 'Mot de passe',
    'Username is required': "Le nom d'utilisateur est requis",
    'Password is required': 'Le mot de passe est requis',
    'Login successful': 'Connexion réussie',
    'Login failed': 'Échec de la connexion',
    "Don't have an account?": "Vous n'avez pas de compte ?",
    'Registration successful': 'Inscription réussie',
    'Registration failed': "Échec de l'inscription",
    'Username must be at least 3 characters': "Le nom d'utilisateur doit contenir au moins 3 caractères",
    'Password must be at least 8 characters': 'Le mot de passe doit contenir au moins 8 caractères',
    'Already have an account?': 'Vous avez déjà un compte ?',
    'Room name is required': 'Le nom du salon est requis',
    'Chat room "{{name}}" created': 'Salon "{{name}}" créé',
    'Failed to create room': 'Échec de la création du salon',
    'Enter room name': 'Entrez le nom du salon',
    'No rooms yet. Create the first one!': "Aucun salon pour l'instant. Créez le premier !",
    'Join': 'Rejoindre',
    'Failed to load rooms': 'Échec du chargement des salons',
    'Failed to load room': 'Échec du chargement du salon',
    'Connection lost': 'Connexion perdue',
    'You': 'Vous',
    'Send Message': 'Envoyer',
    'Loading...': 'Chargement...',
    'Welcome to the Chat Application': "Bienvenue sur l'application de chat",
    'Create an account or log in to join real-time chat rooms.':
      'Créez un compte ou connectez-vous pour rejoindre des salons de discussion en temps réel.',
  },
  de: {
    'Login': 'Anmelden',
    'Register': 'Registrieren',
    'Chat Rooms': 'Chaträume',
    'Create Chat Room': 'Chatraum erstellen',
    'Log Out': 'Abmelden',
    'Language': 'Sprache',
    'Username': 'Benutzername',
    'Password': 'Passwort',
    'Username is required': 'Benutzername ist erforderlich',
    'Password is required': 'Passwort ist erforderlich',
    'Login successful': 'Anmeldung erfolgreich',
    'Login failed': 'Anmeldung fehlgeschlagen',
    "Don't have an account?": 'Noch kein Konto?',
    'Registration successful': 'Registrierung erfolgreich',
    'Registration failed': 'Registrierung fehlgeschlagen',
    'Username must be at least 3 characters': 'Der Benutzername muss mindestens 3 Zeichen lang sein',
    'Password must be at least 8 characters': 'Das Passwort muss mindestens 8 Zeichen lang sein',
    'Already have an account?': 'Bereits ein Konto?',
    'Room name is required': 'Raumname ist erforderlich',
    'Chat room "{{name}}" created': 'Chatraum "{{name}}" erstellt',
    'Failed to create room': 'Raum konnte nicht erstellt werden',
    'Enter room name': 'Raumnamen eingeben',
    'No rooms yet. Create the first one!': 'Noch keine Räume. Erstelle den ersten!',
    'Join': 'Beitreten',
    'Failed to load rooms': 'Räume konnten nicht geladen werden',
    'Failed to load room': 'Raum konnte nicht geladen werden',
    'Connection lost': 'Verbindung verloren',
    'You': 'Du',
    'Send Message': 'Nachricht senden',
    'Loading...': 'Lädt...',
    'Welcome to the Chat Application': 'Willkommen bei der Chat-Anwendung',
    'Create an account or log in to join real-time chat rooms.':
      'Erstelle ein Konto oder melde dich an, um Echtzeit-Chaträumen beizutreten.',
  },
  it: {
    'Login': 'Accedi',
    'Register': 'Registrati',
    'Chat Rooms': 'Stanze di Chat',
    'Create Chat Room': 'Crea Stanza di Chat',
    'Log Out': 'Disconnetti',
    'Language': 'Lingua',
    'Username': 'Nome utente',
    'Password': 'Password',
    'Username is required': 'Il nome utente è obbligatorio',
    'Password is required': 'La password è obbligatoria',
    'Login successful': 'Accesso effettuato con successo',
    'Login failed': 'Accesso non riuscito',
    "Don't have an account?": 'Non hai un account?',
    'Registration successful': 'Registrazione avvenuta con successo',
    'Registration failed': 'Registrazione non riuscita',
    'Username must be at least 3 characters': 'Il nome utente deve contenere almeno 3 caratteri',
    'Password must be at least 8 characters': 'La password deve contenere almeno 8 caratteri',
    'Already have an account?': 'Hai già un account?',
    'Room name is required': 'Il nome della stanza è obbligatorio',
    'Chat room "{{name}}" created': 'Stanza "{{name}}" creata',
    'Failed to create room': 'Impossibile creare la stanza',
    'Enter room name': 'Inserisci il nome della stanza',
    'No rooms yet. Create the first one!': 'Nessuna stanza ancora. Crea la prima!',
    'Join': 'Entra',
    'Failed to load rooms': 'Impossibile caricare le stanze',
    'Failed to load room': 'Impossibile caricare la stanza',
    'Connection lost': 'Connessione persa',
    'You': 'Tu',
    'Send Message': 'Invia Messaggio',
    'Loading...': 'Caricamento...',
    'Welcome to the Chat Application': "Benvenuto nell'applicazione di chat",
    'Create an account or log in to join real-time chat rooms.':
      'Crea un account o accedi per unirti a stanze di chat in tempo reale.',
  },
  pl: {
    'Login': 'Zaloguj się',
    'Register': 'Zarejestruj się',
    'Chat Rooms': 'Pokoje czatu',
    'Create Chat Room': 'Utwórz pokój czatu',
    'Log Out': 'Wyloguj się',
    'Language': 'Język',
    'Username': 'Nazwa użytkownika',
    'Password': 'Hasło',
    'Username is required': 'Nazwa użytkownika jest wymagana',
    'Password is required': 'Hasło jest wymagane',
    'Login successful': 'Logowanie powiodło się',
    'Login failed': 'Logowanie nie powiodło się',
    "Don't have an account?": 'Nie masz konta?',
    'Registration successful': 'Rejestracja zakończona sukcesem',
    'Registration failed': 'Rejestracja nie powiodła się',
    'Username must be at least 3 characters': 'Nazwa użytkownika musi mieć co najmniej 3 znaki',
    'Password must be at least 8 characters': 'Hasło musi mieć co najmniej 8 znaków',
    'Already have an account?': 'Masz już konto?',
    'Room name is required': 'Nazwa pokoju jest wymagana',
    'Chat room "{{name}}" created': 'Utworzono pokój "{{name}}"',
    'Failed to create room': 'Nie udało się utworzyć pokoju',
    'Enter room name': 'Wpisz nazwę pokoju',
    'No rooms yet. Create the first one!': 'Brak pokoi. Utwórz pierwszy!',
    'Join': 'Dołącz',
    'Failed to load rooms': 'Nie udało się wczytać pokoi',
    'Failed to load room': 'Nie udało się wczytać pokoju',
    'Connection lost': 'Utracono połączenie',
    'You': 'Ty',
    'Send Message': 'Wyślij wiadomość',
    'Loading...': 'Ładowanie...',
    'Welcome to the Chat Application': 'Witamy w aplikacji czatu',
    'Create an account or log in to join real-time chat rooms.':
      'Załóż konto lub zaloguj się, aby dołączyć do pokojów czatu w czasie rzeczywistym.',
  },
  ru: {
    'Login': 'Войти',
    'Register': 'Зарегистрироваться',
    'Chat Rooms': 'Чат-комнаты',
    'Create Chat Room': 'Создать комнату',
    'Log Out': 'Выйти',
    'Language': 'Язык',
    'Username': 'Имя пользователя',
    'Password': 'Пароль',
    'Username is required': 'Требуется имя пользователя',
    'Password is required': 'Требуется пароль',
    'Login successful': 'Вход выполнен успешно',
    'Login failed': 'Ошибка входа',
    "Don't have an account?": 'Нет аккаунта?',
    'Registration successful': 'Регистрация прошла успешно',
    'Registration failed': 'Ошибка регистрации',
    'Username must be at least 3 characters': 'Имя пользователя должно содержать не менее 3 символов',
    'Password must be at least 8 characters': 'Пароль должен содержать не менее 8 символов',
    'Already have an account?': 'Уже есть аккаунт?',
    'Room name is required': 'Требуется название комнаты',
    'Chat room "{{name}}" created': 'Комната "{{name}}" создана',
    'Failed to create room': 'Не удалось создать комнату',
    'Enter room name': 'Введите название комнаты',
    'No rooms yet. Create the first one!': 'Комнат пока нет. Создайте первую!',
    'Join': 'Войти',
    'Failed to load rooms': 'Не удалось загрузить комнаты',
    'Failed to load room': 'Не удалось загрузить комнату',
    'Connection lost': 'Соединение потеряно',
    'You': 'Вы',
    'Send Message': 'Отправить',
    'Loading...': 'Загрузка...',
    'Welcome to the Chat Application': 'Добро пожаловать в чат-приложение',
    'Create an account or log in to join real-time chat rooms.':
      'Создайте аккаунт или войдите, чтобы присоединиться к чат-комнатам в реальном времени.',
  },
  zh: {
    'Login': '登录',
    'Register': '注册',
    'Chat Rooms': '聊天室',
    'Create Chat Room': '创建聊天室',
    'Log Out': '登出',
    'Language': '语言',
    'Username': '用户名',
    'Password': '密码',
    'Username is required': '用户名为必填项',
    'Password is required': '密码为必填项',
    'Login successful': '登录成功',
    'Login failed': '登录失败',
    "Don't have an account?": '还没有账户？',
    'Registration successful': '注册成功',
    'Registration failed': '注册失败',
    'Username must be at least 3 characters': '用户名至少需要3个字符',
    'Password must be at least 8 characters': '密码至少需要8个字符',
    'Already have an account?': '已经有账户？',
    'Room name is required': '房间名称为必填项',
    'Chat room "{{name}}" created': '聊天室 "{{name}}" 已创建',
    'Failed to create room': '创建房间失败',
    'Enter room name': '输入房间名称',
    'No rooms yet. Create the first one!': '还没有房间，快创建第一个吧！',
    'Join': '加入',
    'Failed to load rooms': '加载房间失败',
    'Failed to load room': '加载房间失败',
    'Connection lost': '连接已断开',
    'You': '你',
    'Send Message': '发送消息',
    'Loading...': '加载中...',
    'Welcome to the Chat Application': '欢迎使用聊天应用',
    'Create an account or log in to join real-time chat rooms.': '创建账户或登录以加入实时聊天室。',
  },
  hi: {
    'Login': 'लॉग इन करें',
    'Register': 'पंजीकरण करें',
    'Chat Rooms': 'चैट रूम',
    'Create Chat Room': 'चैट रूम बनाएँ',
    'Log Out': 'लॉग आउट करें',
    'Language': 'भाषा',
    'Username': 'उपयोगकर्ता नाम',
    'Password': 'पासवर्ड',
    'Username is required': 'उपयोगकर्ता नाम आवश्यक है',
    'Password is required': 'पासवर्ड आवश्यक है',
    'Login successful': 'लॉगिन सफल रहा',
    'Login failed': 'लॉगिन विफल रहा',
    "Don't have an account?": 'खाता नहीं है?',
    'Registration successful': 'पंजीकरण सफल रहा',
    'Registration failed': 'पंजीकरण विफल रहा',
    'Username must be at least 3 characters': 'उपयोगकर्ता नाम कम से कम 3 अक्षरों का होना चाहिए',
    'Password must be at least 8 characters': 'पासवर्ड कम से कम 8 अक्षरों का होना चाहिए',
    'Already have an account?': 'पहले से खाता है?',
    'Room name is required': 'कमरे का नाम आवश्यक है',
    'Chat room "{{name}}" created': 'चैट रूम "{{name}}" बनाया गया',
    'Failed to create room': 'रूम बनाने में विफल',
    'Enter room name': 'रूम का नाम दर्ज करें',
    'No rooms yet. Create the first one!': 'अभी तक कोई रूम नहीं है। पहला बनाएँ!',
    'Join': 'शामिल हों',
    'Failed to load rooms': 'रूम लोड करने में विफल',
    'Failed to load room': 'रूम लोड करने में विफल',
    'Connection lost': 'कनेक्शन टूट गया',
    'You': 'आप',
    'Send Message': 'संदेश भेजें',
    'Loading...': 'लोड हो रहा है...',
    'Welcome to the Chat Application': 'चैट एप्लिकेशन में आपका स्वागत है',
    'Create an account or log in to join real-time chat rooms.':
      'रीयल-टाइम चैट रूम में शामिल होने के लिए खाता बनाएँ या लॉग इन करें।',
  },
  ar: {
    'Login': 'تسجيل الدخول',
    'Register': 'التسجيل',
    'Chat Rooms': 'غرف الدردشة',
    'Create Chat Room': 'إنشاء غرفة دردشة',
    'Log Out': 'تسجيل الخروج',
    'Language': 'اللغة',
    'Username': 'اسم المستخدم',
    'Password': 'كلمة المرور',
    'Username is required': 'اسم المستخدم مطلوب',
    'Password is required': 'كلمة المرور مطلوبة',
    'Login successful': 'تم تسجيل الدخول بنجاح',
    'Login failed': 'فشل تسجيل الدخول',
    "Don't have an account?": 'ليس لديك حساب؟',
    'Registration successful': 'تم التسجيل بنجاح',
    'Registration failed': 'فشل التسجيل',
    'Username must be at least 3 characters': 'يجب أن يتكون اسم المستخدم من 3 أحرف على الأقل',
    'Password must be at least 8 characters': 'يجب أن تتكون كلمة المرور من 8 أحرف على الأقل',
    'Already have an account?': 'هل لديك حساب بالفعل؟',
    'Room name is required': 'اسم الغرفة مطلوب',
    'Chat room "{{name}}" created': 'تم إنشاء غرفة "{{name}}"',
    'Failed to create room': 'فشل إنشاء الغرفة',
    'Enter room name': 'أدخل اسم الغرفة',
    'No rooms yet. Create the first one!': 'لا توجد غرف بعد. أنشئ الأولى!',
    'Join': 'انضمام',
    'Failed to load rooms': 'فشل تحميل الغرف',
    'Failed to load room': 'فشل تحميل الغرفة',
    'Connection lost': 'انقطع الاتصال',
    'You': 'أنت',
    'Send Message': 'إرسال رسالة',
    'Loading...': 'جارٍ التحميل...',
    'Welcome to the Chat Application': 'مرحبًا بك في تطبيق الدردشة',
    'Create an account or log in to join real-time chat rooms.':
      'أنشئ حسابًا أو سجّل الدخول للانضمام إلى غرف الدردشة في الوقت الفعلي.',
  },
};

const resources = Object.fromEntries(
  Object.entries(keys).map(([lang, translation]) => [lang, { translation }])
);

i18n.use(initReactI18next).init({
  resources,
  lng: 'en',
  fallbackLng: 'en',
  interpolation: {
    escapeValue: false, // React already escapes values
  },
});

export default i18n;
